# Generated by Django 2.1.7 on 2019-03-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('servernumber', models.IntegerField()),
                ('owner', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('system', models.CharField(choices=[('redhat', 'redhat'), ('opensuse', 'opensuse'), ('ubuntu', 'ubuntu'), ('centos', 'centos'), ('windows', 'windows'), ('other', 'other')], default='centos', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cpuinfo', models.CharField(max_length=50)),
                ('memory', models.IntegerField()),
                ('status', models.CharField(choices=[('produce', 'produce'), ('test', 'test'), ('other', 'other')], default='other', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Category')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project')),
            ],
        ),
    ]
